
spring.security.user.name=disabled
logging.level.org.springframework.security=DEBUG
spring.application.name=ashwbank
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ashwbank_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=$Uju1432
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ashwbank-super-secret-jwt-key-2026-ashwajeet
jwt.expiration=86400000

